#!/bin/bash
#Author: Harsha
#Date: 16-11-2022
#Description: This script installs jenkins in your Redhat Linux
#Modified: 17-11-2022

#Run this script as root user from Red Hat linux

sudo -i
yum update -y
yum install git -y
yum install fontconfig java-11-openjdk -y
sudo amazon-linux-extras install java-openjdk11
yum install maven -y
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
yum install jenkins -y
systemctl start jenkins 
