#!/bin/bash
#Author: Harsha
#Date: 16-11-2022
#Description: This script installs jenkins in your Redhat Linux
#Modified: 17-11-2022

#Run this script as root user from Red Hat linux

yum update -y
yum install git -y
yum install fontconfig java-11-openjdk -y
sudo amazon-linux-extras install java-openjdk11 -y
yum install maven -y
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
yum install jenkins -y
sudo su -
echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.16.0.8-1.amzn2.0.1.x86_64" >> .bash_profile
echo "M2_HOME=/usr/share/maven" >> .bash_profile
echo "M2=/usr/share/maven/bin" >> .bash_profile
echo "PATH=$PATH:$HOME/bin:$M2:$M2_HOME:$JAVA_HOME" >> .bash_profile

source .bash_profile

systemctl start jenkins 

